#!/bin/bash

#
# usage: $ snakemake -np mapped_reads/A.bam
#          snakemake --cores 1 mapped_reads/A.bam


rule bwa_map:
    input:
        "../data/genome.fa",
        "../data/samples/A.fastq"
    output:
        "../mapped_reads/A.bam"
    shell:
    '''
        module load bwa-mem

        bwa mem {input} | samtools view -Sb - > {output}
'''
