#!/bin/bash

#SBATCH -J hg19.genome
#SBATCH -p defq
#SBATCH --time=2:00:00
#SBATCH --cpus-per-task=1
#SBATCH --output=hg19.genome.job.%j.out

module load samtools/1.15.1

curl http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz | tar xzvf -

cat *.fa > hg19.fa.tmp
rm -f *.fa
mv hg19.fa.tmp hg19.fa

samtools faidx hg19.fa


